### ISSUE TITLE
Include Cancellation Reason in Subscription Cancellation Message

### ISSUE THREAD

**Issue by v2theg** [Prospress/woocommerce-subscriptions-cancel-subscription-confirmation#13]
Is it possible to add the Cancellation Reason in the Subscription Cancellation email notification?

**Comment by jrick1229** [comment]
Hi @v2theg - That type of behavior would require further development. I would suggest contacting a private developer of submitting a PR if you are interested in furthering the functionality of this free plugin.

- Joey

**Comment by v2theg** [comment]
Thanks!
